# Generated by Django 5.0.4 on 2024-04-18 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='financial_goals',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_of_establishment',
            field=models.DateField(null=True, verbose_name='date of establishment'),
        ),
    ]
