# Generated by Django 5.0.4 on 2024-04-18 21:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customuser_financial_goals_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='date_of_establishment',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='type_of_business',
        ),
        migrations.AddField(
            model_name='customuser',
            name='reason_for_signup',
            field=models.CharField(choices=[('To gain financial literacy', 'To gain financial literacy'), ('To access financial service', 'To access financial service')], max_length=50, null=True, verbose_name='reason for signup'),
        ),
        migrations.CreateModel(
            name='SMERegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=50, null=True)),
                ('business_id', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=50, null=True)),
                ('type_of_business', models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], max_length=50, null=True)),
                ('date_of_establishment', models.DateField(null=True, verbose_name='date of establishment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
