-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.account_customuser
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    password character varying(128) COLLATE pg_catalog."default" NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) COLLATE pg_catalog."default" NOT NULL,
    first_name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    last_name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    email character varying(254) COLLATE pg_catalog."default" NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    gender character varying(50) COLLATE pg_catalog."default",
    date_of_birth date,
    occupation character varying(50) COLLATE pg_catalog."default",
    business_owner boolean,
    income_per_month character varying(50) COLLATE pg_catalog."default",
    type_of_business character varying(50) COLLATE pg_catalog."default",
    date_of_establishment date,
    CONSTRAINT account_customuser_pkey PRIMARY KEY (id),
    CONSTRAINT account_customuser_username_key UNIQUE (username)
);

CREATE TABLE IF NOT EXISTS public.account_customuser_groups
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    customuser_id bigint NOT NULL,
    group_id integer NOT NULL,
    CONSTRAINT account_customuser_groups_pkey PRIMARY KEY (id),
    CONSTRAINT account_customuser_groups_customuser_id_group_id_7e51db7b_uniq UNIQUE (customuser_id, group_id)
);

CREATE TABLE IF NOT EXISTS public.bank_bank
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    services text COLLATE pg_catalog."default" NOT NULL,
    logo character varying(100) COLLATE pg_catalog."default",
    link character varying(100) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    category_id bigint,
    CONSTRAINT bank_bank_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.bank_financialservicecategory
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    desscription text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT bank_financialservicecategory_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.coarse_coarse
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default" NOT NULL,
    image character varying(100) COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT coarse_coarse_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.coarse_content_coarsecontent
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    notes text COLLATE pg_catalog."default" NOT NULL,
    video character varying(100) COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    coarse_id bigint NOT NULL,
    CONSTRAINT coarse_content_coarsecontent_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.coarse_enrollment_coarseenrollment
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    status character varying(10) COLLATE pg_catalog."default" NOT NULL,
    progress numeric(3, 3),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    coarse_id bigint,
    user_id bigint NOT NULL,
    CONSTRAINT coarse_enrollment_coarseenrollment_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.home_sitedetails
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    logo character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT home_sitedetails_pkey PRIMARY KEY (id)
);
END;