# Generated by Django 5.0.4 on 2024-04-18 19:03

import app.storage_backend
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('services', models.TextField()),
                ('logo', models.ImageField(blank=True, null=True, storage=app.storage_backend.PublicMediaStorage(), upload_to='')),
                ('link', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('business_type', models.CharField(max_length=100)),
                ('service_provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bank.financialserviceprovider')),
            ],
        ),
        migrations.CreateModel(
            name='LoanService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('business_type', models.CharField(max_length=100)),
                ('service_provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bank.financialserviceprovider')),
            ],
        ),
        migrations.DeleteModel(
            name='Bank',
        ),
        migrations.DeleteModel(
            name='FinancialServiceCategory',
        ),
    ]
