# Generated by Django 5.0.4 on 2024-04-18 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_financialserviceprovider_investmentservice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentservice',
            name='eligibility_criteria',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investmentservice',
            name='expected_return_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='investmentservice',
            name='min_income_required',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='investmentservice',
            name='min_investment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='loanservice',
            name='eligibility_criteria',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanservice',
            name='interest_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='loanservice',
            name='max_loan_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='loanservice',
            name='min_income_required',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='loanservice',
            name='min_loan_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
