# Generated by Django 5.0.1 on 2024-03-13 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coarse', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coarse',
            options={},
        ),
        migrations.AlterField(
            model_name='coarse',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='coarse',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
