# Generated by Django 5.0.1 on 2024-04-09 17:26

import app.storage_backend
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coarse', '0002_alter_coarse_options_alter_coarse_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coarse',
            name='image',
            field=models.ImageField(null=True, storage=app.storage_backend.PublicMediaStorage(), upload_to=''),
        ),
    ]
