# Generated by Django 5.0.1 on 2024-03-13 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coarse', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoarseContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('notes', models.TextField()),
                ('video', models.FileField(null=True, upload_to='coarse_content/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coarse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coarse.coarse')),
            ],
        ),
    ]
