# Generated by Django 5.0.1 on 2024-04-17 23:54

import app.storage_backend
import django.db.models.deletion
import martor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coarse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoarseContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('notes', martor.models.MartorField()),
                ('video', models.FileField(null=True, storage=app.storage_backend.PublicMediaStorage(), upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coarse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coarse.coarse')),
            ],
        ),
    ]
