# Generated by Django 5.0.1 on 2024-03-24 23:02

import martor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coarse_content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coarsecontent',
            name='notes',
            field=martor.models.MartorField(),
        ),
    ]
