# Generated by Django 5.0.1 on 2024-04-09 17:26

import app.storage_backend
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coarse_content', '0002_alter_coarsecontent_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coarsecontent',
            name='video',
            field=models.FileField(null=True, storage=app.storage_backend.PublicMediaStorage(), upload_to=''),
        ),
    ]
