# Generated by Django 5.0.1 on 2024-02-19 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_healthspecialist_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthspecialist',
            name='avatar',
            field=models.ImageField(default='medical_specialists/doctor.png', null=True, upload_to='medical_specialists/'),
        ),
    ]
