# Generated by Django 5.0.1 on 2024-03-09 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_healthspecialist_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthspecialist',
            name='city',
        ),
        migrations.RemoveField(
            model_name='healthfacility',
            name='city',
        ),
        migrations.RemoveField(
            model_name='healthspecialist',
            name='contact_info',
        ),
        migrations.RemoveField(
            model_name='healthfacility',
            name='contact_info',
        ),
        migrations.RemoveField(
            model_name='healthfacility',
            name='category',
        ),
        migrations.RemoveField(
            model_name='healthspecialist',
            name='medical_specialty',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='HealthFacility',
        ),
        migrations.DeleteModel(
            name='HealthFacilityCategory',
        ),
        migrations.DeleteModel(
            name='HealthSpecialist',
        ),
        migrations.DeleteModel(
            name='MedicalSpecialty',
        ),
    ]
