# Generated by Django 5.0.1 on 2024-04-11 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SiteDetaisl',
            new_name='SiteDetails',
        ),
    ]
