# Generated by Django 5.0.4 on 2024-04-20 12:54

import app.storage_backend
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('services', models.TextField()),
                ('logo', models.ImageField(blank=True, null=True, storage=app.storage_backend.PublicMediaStorage(), upload_to='')),
                ('link', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('business_type', models.CharField(max_length=100)),
                ('min_investment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('expected_return_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('eligibility_criteria', models.TextField(blank=True, null=True)),
                ('min_income_required', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('service_provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='financial_service.financialserviceprovider')),
            ],
        ),
        migrations.CreateModel(
            name='LoanService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('business_type', models.CharField(max_length=100)),
                ('min_loan_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_loan_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('eligibility_criteria', models.TextField(blank=True, null=True)),
                ('min_income_required', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('service_provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='financial_service.financialserviceprovider')),
            ],
        ),
    ]
