# Generated by Django 5.0.1 on 2024-03-13 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coarse', '__first__'),
        ('student', '0007_alter_student_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoarseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('REVOKED', 'Revoked'), ('COMPLETED', 'Completed')], default='PENDING', max_length=10)),
                ('progress', models.DecimalField(decimal_places=3, max_digits=3, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coarse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coarse.coarse')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
