# Generated by Django 5.0.1 on 2024-03-10 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coarse_enrollment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coarseenrollment',
            name='coarse',
            field=models.ManyToManyField(to='coarse.coarse'),
        ),
    ]
