# Generated by Django 5.0.1 on 2024-03-10 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coarse_enrollment', '0002_coarseenrollment_coarse'),
        ('student', '0007_alter_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='coarseenrollment',
            name='progress',
            field=models.DecimalField(decimal_places=3, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='coarseenrollment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('REVOKED', 'Revoked'), ('COMPLETED', 'Completed')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='coarseenrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student'),
        ),
    ]
