# Generated by Django 5.0.1 on 2024-04-17 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coarse_enrollment', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coarseenrollment',
            old_name='student',
            new_name='user',
        ),
    ]
