# Generated by Django 5.0.1 on 2024-03-13 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coarse', '__first__'),
        ('coarse_enrollment', '0003_coarseenrollment_progress_coarseenrollment_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coarseenrollment',
            name='coarse',
        ),
        migrations.AddField(
            model_name='coarseenrollment',
            name='coarse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coarse.coarse'),
        ),
    ]
