# Generated by Django 5.0.1 on 2024-03-13 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coarse_enrollment', '0004_remove_coarseenrollment_coarse_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoarseEnrollment',
        ),
    ]
