# Generated by Django 5.0.1 on 2024-03-10 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_student_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
